### ISSUE TITLE
Request for PSV PSO2 6.30 Patch Backup

### ISSUE THREAD

**Issue by Sancaros** [PhantasyServer/phantasyserver#29]
Dear Anton,
I hope this message finds you well.
I am reaching out to kindly request a backup of the PSV PSO2 6.30 patch. Unfortunately, I am currently unable to locate the patch, and I would greatly appreciate it if you could send me a copy at your earliest convenience.
Thank you in advance for your time and assistance. Should you require any further details, please feel free to let me know.
Looking forward to your reply.
Best regards,
[Sancaros]

**Comment by AntonnMal** [comment]
Please see #18 (in particular [this](https://github.com/PhantasyServer/phantasyserver/issues/18#issuecomment-2202783612) comment)

**Comment by Sancaros** [comment]
Thank you very much!
