### ISSUE TITLE
Extract the sy_script.fpk file

### ISSUE THREAD

**Issue by Sancaros** [PhantasyServer/phantasyserver#30]
I'm sorry to bother you again. I would like to ask you how to decompress the fpk file. About what you said: Extract the sy_script.fpk file
For this sentence, I have found relevant tools, but the sy_script.fpk file I obtained from app or patch seems to be encrypted, could you please teach me? Thank you very much.

**Comment by AntonnMal** [comment]
Once you have copied the patch set to the patch folder in VitaShell there is an `Open decrypted` option. Using that will give you the decrypted view of the folder. All you have to do then is copy the decrypted `fpk` file somewhere else and upload it to your pc

**Comment by Sancaros** [comment]
Thank you very much. It is my first time to contact PSV, and I do not know much about the use of the software. Thank you for your guidance
