### ISSUE TITLE
Dev-protocol PSV cannot login on Authentication SEGAID

### ISSUE THREAD

**Issue by Sancaros** [PhantasyServer/phantasyserver#31]
![331859F9D21153C81054A8E510C07C2E](https://github.com/user-attachments/assets/a3656d59-711e-451a-8990-419858fea1a5)
how to fix error C2-12828-1

In addition, I have developed your latest code in multiple languages. If you are interested, can I use discord to communicate with you about development

**Comment by zmbkilla** [comment]
iirc, that just means the game crashed. The cause could be anything.

**Comment by AntonnMal** [comment]
When does the game crash? After trying to connect to a ship or before ship selection screen appears?
If it's the former then probably something is wrong with the RSA key. If it's the latter then most likely something is wrong with the `sy_script.fpk` (e.g. improper replacement of the IP addresses)

**Comment by zmbkilla** [comment]
Going by screenshot it seems to be when loading the ship list

**Comment by AntonnMal** [comment]
> Going by screenshot it seems to be when loading the ship list

Not necessarily. I've just double checked and when selecting a ship to connect to the header doesn't change

**Comment by Sancaros** [comment]
Sorry for the late reply. I just came back from the communication equipment room. This was an error reported during login authentication after selecting the ship list, and the same situation occurred on the PC side. The server version is DEV protocol

**Comment by Sancaros** [comment]
Because I am also continuing to develop the Polaris server, I have confirmed that there are no errors with RSA. I will try comparing the code to see where the error occurred

**Comment by AntonnMal** [comment]
Aha, then I have a hunch. Try to rebuild the compiled data
```
cargo run --bin=data_compiler --release data
```

**Comment by AntonnMal** [comment]
The client **really** doesn't like malformed item attributes packet, so I think that is the problem

**Comment by Sancaros** [comment]
Currently, it's quite strange that even after using your latest dev protocol code and recompiling it according to the process, the client still crashes when logging in

**Comment by Sancaros** [comment]
match_unit: (LoggingIn, EncryptionRequest(EncryptionRequestPacket { rsa_data: Bytes { bytes: [124, 218, 44, 190, 166, 114, 32, 221, 89, 37, 181, 166, 180, 245, 206, 172, 52, 174, 189, 32, 6, 216, 64, 220, 246, 191, 113, 76, 223, 67, 125, 212, 14, 105, 1, 220, 241, 169, 175, 130, 70, 115, 216, 238, 253, 191, 143, 120, 47, 16, 50, 167, 195, 127, 84, 152, 230, 87, 91, 71, 118, 133, 187, 234, 191, 190, 108, 246, 143, 200, 105, 48, 211, 250, 27, 135, 70, 206, 205, 15, 0, 0, 0, 0] } }))
match_unit: (LoggingIn, SegaIDLogin(SegaIDLoginPacket { unk1: 0, unk2: 9, unk3: 1615745028, ver_id: [66, 197, 52, 69, 48, 104, 227, 202, 134, 60, 41, 168, 3, 126, 48, 111, 128, 158, 76, 77, 89, 77, 102, 238, 123, 208, 1, 171, 5, 194, 216, 75], interfaces: [NetInterface { state: 6, mac: FixedAsciiString { string: "10-FF-E0-11-42-D7" } }, NetInterface { state: 24, mac: FixedAsciiString { string: "" } }], unk4: FixedBytes { bytes: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }, unk5: [74, 231, 19, 54, 228, 75, 249, 191, 121, 210, 117, 46, 35, 72, 24, 165], text_lang: English, voice_lang: English, text_lang2: English, lang_lang: English, language: FixedString { string: "CHN" }, unk6: 86, unk7: 8, magic1: 2052, unk8: [15, 15, 12, 6, 14, 18, 8, 15, 15, 10, 10, 18, 12, 14, 13, 14, 14, 18, 126, 126, 9, 8, 10, 63, 0, 0, 0, 0, 0, 0, 0, 0], unk9: FixedBytes { bytes: [186, 168, 193, 89, 85, 73, 242, 182, 237, 135, 243, 34, 213, 218, 20, 141, 35, 60, 145, 203, 65, 21, 59, 21, 92, 21, 91, 21, 69, 21, 64, 21, 65, 21, 93, 21, 90, 21, 70, 21, 65, 21, 59, 21, 81, 21, 89, 21, 89, 21, 21, 21, 166, 90, 167, 181, 161, 69, 160, 180, 231, 163, 114, 162, 165, 173, 165, 172] }, username: FixedAsciiString { string: "sancaros" }, password: FixedAsciiString { string: "*************" }, unk10: 512, unk11: "" }))
match_unit: (CharacterSelect, ClientPing(ClientPingPacket { time: WinTime { time: 10536467768.955s } }))

then the client crashed

**Comment by zmbkilla** [comment]
> Because I am also continuing to develop the Polaris server, I have confirmed that there are no errors with RSA. I will try comparing the code to see where the error occurred

That's cool. How far have you got your's?

**Comment by AntonnMal** [comment]
The problem with the current `dev-protocol` branch is that there was a [massive change](https://github.com/PhantasyServer/pso2-protocol-lib/commit/8e08e879ae41ca903b33009400dba13bd91162d4) to the code of the protocol lib, so something went wrong with the item attributes struct. Gonna look into that now

**Comment by Sancaros** [comment]
> > Because I am also continuing to develop the Polaris server, I have confirmed that there are no errors with RSA. I will try comparing the code to see where the error occurred
> 
> That's cool. How far have you got your branch?

http://sanc.top:3000/PSO2SERVER/PSO2SERVER.git if you are interesting but this version the character packet stil WIP

**Comment by zmbkilla** [comment]
Oh I'm helping out with another Pserver. Just needed to understand the Vita packets cause on my build, the client crashes with the same error as Sancaros on initial load packet. I think it might be related to the item struct but I want to try checking this one out to see where I went wrong.

**Comment by zmbkilla** [comment]
> > > Because I am also continuing to develop the Polaris server, I have confirmed that there are no errors with RSA. I will try comparing the code to see where the error occurred
> > 
> > 
> > That's cool. How far have you got your branch?
> 
> http://sanc.top:3000/PSO2SERVER/PSO2SERVER.git if you are interesting but this version the character packet stil WIP

Character packet? is this the character list packet?

**Comment by Sancaros** [comment]
> > > > Because I am also continuing to develop the Polaris server, I have confirmed that there are no errors with RSA. I will try comparing the code to see where the error occurred
> > > 
> > > 
> > > That's cool. How far have you got your branch?
> > 
> > 
> > http://sanc.top:3000/PSO2SERVER/PSO2SERVER.git if you are interesting but this version the character packet stil WIP
> 
> Character packet? is this the character list packet?

Protocol 0x08 0x04 CharacterSpawnPacket

**Comment by Sancaros** [comment]
> > > > > Because I am also continuing to develop the Polaris server, I have confirmed that there are no errors with RSA. I will try comparing the code to see where the error occurred
> > > > 
> > > > 
> > > > That's cool. How far have you got your branch?
> > > 
> > > 
> > > http://sanc.top:3000/PSO2SERVER/PSO2SERVER.git if you are interesting but this version the character packet stil WIP
> > 
> > 
> > Character packet? is this the character list packet?
> 
> Protocol 0x08 0x04 CharacterSpawnPacket

and Protocol 0x11 0x03 CharacterListPacket

**Comment by Sancaros** [comment]
> The problem with the current `dev-protocol` branch is that there was a [massive change](https://github.com/PhantasyServer/pso2-protocol-lib/commit/8e08e879ae41ca903b33009400dba13bd91162d4) to the code of the protocol lib, so something went wrong with the item attributes struct. Gonna look into that now

Thank you for pointing out the modifications. I have seen a lot of changes, so I will try to understand your changes first

**Comment by AntonnMal** [comment]
Ok, so I think I've fixed the problem. Try force pulling the latest commit in the `dev-protocol` branch and see if it works

**Comment by Sancaros** [comment]
Nice work!Authentication SEGAID Problem Solved.
