### ISSUE TITLE
Having issues with RCA blob

### ISSUE THREAD

**Issue by zmbkilla** [PhantasyServer/phantasyserver#32]
Hi! Was able to setup both the master server and the ship server but having errors with the key exchange
Image:
![image](https://github.com/user-attachments/assets/4bec1613-efef-40cc-8016-1521ce616f5e)
Keypair.pem was generated from masterserver

**Comment by AntonnMal** [comment]
There is not a whole lot of information here:
 - How are you injecting the RSA key into the client?
 - If you are using [this](https://github.com/PhantasyServer/pso2-rsa-injector-classic) injector, have you enabled `auto_key_fetch` or have you copied the key to the game folder?
 
Also the master ship does not generate `keypair.pem`

P.S. I've forgot to push update to the injector that fixes key negotiation, pushing now

**Comment by zmbkilla** [comment]
Hello. For the stuff you asked for:
- Currently using iirc version 0.7.0 (Before the split between NGS and classic injector)
- ![image](https://github.com/user-attachments/assets/b64c6d34-65d1-4866-b841-0b33cad6c14d)
I'll update the injector and config file.

**Comment by zmbkilla** [comment]
Oh no. Updated my build using latest develop branch and I get this error with shipserver
![image](https://github.com/user-attachments/assets/95a2062f-89ef-4636-9d66-dcb7f1885422)

**Comment by AntonnMal** [comment]
Can you recheck `registration_enabled` in the master ship config?

**Comment by zmbkilla** [comment]
![image](https://github.com/user-attachments/assets/4c7c8fa5-7940-4356-bc3c-917fc94a0791)
Here's the screenshot

**Comment by AntonnMal** [comment]
> EDIT: wait I dont seem to have the psk file. Do I have to download/generate that file?

Uhh, no. It's a password for ship communication set in the `ship.toml` config file. Maybe you've used a different one before and now it's changed. Try deleting master ship DB file

**Comment by zmbkilla** [comment]
Deleted `master_ship.db`, still gives me the psk error but added a new line.
![image](https://github.com/user-attachments/assets/3020cdff-2ea9-4866-8901-cd42fd69a14c)

**Comment by AntonnMal** [comment]
Wait, where are the config files located?

**Comment by zmbkilla** [comment]
Same directory as the exe's.

**Comment by zmbkilla** [comment]
Fixed the issue. Notepad++ wasn't saving my changes for some reason.
sorry. Will update injector next

**Comment by AntonnMal** [comment]
> Fixed the issue. Notepad++ wasn't saving my changes for some reason so had to save through notepad.

Another one bites the dust ([context](https://github.com/PhantasyServer/phantasyserver/issues/18#issuecomment-2212318237))

**Comment by zmbkilla** [comment]
Ok. tried to generate a new public key from the generated `keypair.pem` but I keep getting this line. (don't mind the directory. did not rename folder)
![image](https://github.com/user-attachments/assets/e9c1acb3-32a9-4a77-bd00-ae16f1fc69b7)
![image](https://github.com/user-attachments/assets/a1815974-feaa-4572-a338-9ef4b6e9618a)

**Comment by AntonnMal** [comment]
Try `-outform "MS PUBLICKEYBLOB"` (maybe the other way doesn't work on windows)

**Comment by zmbkilla** [comment]
It worked. Also while I am still fixing client not loading injector, was able to bypass it by editing memory address where the key was located in Cheat Engine. Progress at least.
![image](https://github.com/user-attachments/assets/dece61a4-5e8d-46d0-b0ce-2c0108b1d131)

**Comment by Sancaros** [comment]
Regarding the authentication issue with RSA, I solved it by directly using the injector to inject it, without having to manually inject RSA

config.toml
user_key = "publicKey.blob"
grab_keys = false
**replace_address = true
auto_key_fetch = true**
classic_wine_fix = false
unmd5 = false

[[addresses]]
old = "gs0100.westus2.cloudapp.azure.com"
new = "127.0.0.1"

[[addresses]]
old = "gs0200.westus2.cloudapp.azure.com"
new = "127.0.0.1"

[[addresses]]
old = "gs0300.westus2.cloudapp.azure.com"
new = "127.0.0.1"

[[addresses]]
old = "gs0400.westus2.cloudapp.azure.com"
new = "127.0.0.1"

[[addresses]]
old = "gs0500.westus2.cloudapp.azure.com"
new = "127.0.0.1"

[[addresses]]
old = "gs0600.westus2.cloudapp.azure.com"
new = "127.0.0.1"

**Comment by AntonnMal** [comment]
As the original problem was fixed, I'll be closing this issue. If you have any more problems, feel free to open a new issue
