### ISSUE TITLE
700020 - A Mysterious Voice EP1 Story Issues

### ISSUE THREAD

**Issue by Sancaros** [PhantasyServer/phantasyserver#33]
![QQ20241223-061544](https://github.com/user-attachments/assets/4ee827fe-3944-4615-adfc-70e2f535af37)

Server Version:dev-protocol

Protocol Version:dev-protocol

When the cutscene for the second task of EP1 is completed, you will return to a task selection interface. If you cancel and continue the task, the previous version will return to the lobby, but this time it will keep loading the animation and cannot return to the lobby

**Comment by AntonnMal** [comment]
I'm well aware of this problem, this will occur with any story quest right now. I didn't have the time to look into the packet flow of the exit sequence.

**Comment by Sancaros** [comment]
Okay, I'll see if I can be helpful and try checking the packet flow to see where the problem lies
